highlight_color: "#8E44AD;" 
highlight-dark-color: "#5340BA;"
darker-color: "#C6B7B2;" 
darker-dark-color: "#A8A8A8;"
background-colour: "#F2F2F2;"
alt-link-color: "#BA4082;"
warning-color: "#D13D43;"
