language: objective-c
install:
  - brew remove --force xctool
  - brew install xctool --HEAD

script:
  - xctool test -workspace Demo/HNKWordLookup-Demo.xcworkspace -scheme HNKWordLookup-Demo -sdk iphonesimulator8.1
